package com.therighthandapp.agentmesh.agents.developer.domain;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.Builder;
import lombok.Value;
import lombok.With;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Domain Model: CodeArtifact
 * 
 * Represents code generated by the Developer Agent.
 * This is an immutable value object that encapsulates source code files,
 * dependencies, build configuration, and quality metrics.
 * 
 * DDD: Rich domain model with business logic for validation.
 */
@Value
@Builder
@With
@JsonDeserialize(builder = CodeArtifact.CodeArtifactBuilder.class)
public class CodeArtifact {
    
    String artifactId;
    String planId;
    String architectureId;
    String projectTitle;
    LocalDateTime createdAt;
    
    List<SourceFile> sourceFiles;
    List<Dependency> dependencies;
    BuildConfiguration buildConfig;
    QualityMetrics qualityMetrics;
    
    Map<String, String> metadata;
    
    @JsonPOJOBuilder(withPrefix = "")
    public static class CodeArtifactBuilder {}
    
    /**
     * Source file representation
     */
    @Value
    @Builder
    @JsonDeserialize(builder = SourceFile.SourceFileBuilder.class)
    public static class SourceFile {
        String filePath;
        String fileName;
        String language;
        String content;
        List<String> imports;
        int lineCount;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class SourceFileBuilder {}
        
        public boolean isTestFile() {
            return filePath.contains("/test/") || fileName.endsWith("Test.java");
        }
    }
    
    /**
     * Dependency representation
     */
    @Value
    @Builder
    @JsonDeserialize(builder = Dependency.DependencyBuilder.class)
    public static class Dependency {
        String groupId;
        String artifactId;
        String version;
        String scope; // compile, test, runtime
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class DependencyBuilder {}
        
        public String toMavenFormat() {
            return String.format("%s:%s:%s", groupId, artifactId, version);
        }
    }
    
    /**
     * Build configuration
     */
    @Value
    @Builder
    @JsonDeserialize(builder = BuildConfiguration.BuildConfigurationBuilder.class)
    public static class BuildConfiguration {
        String buildTool; // maven, gradle, npm
        String javaVersion;
        String targetRuntime;
        List<String> buildPlugins;
        Map<String, String> properties;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class BuildConfigurationBuilder {}
    }
    
    /**
     * Code quality metrics
     */
    @Value
    @Builder
    @JsonDeserialize(builder = QualityMetrics.QualityMetricsBuilder.class)
    public static class QualityMetrics {
        int totalLines;
        int codeLines;
        int commentLines;
        double commentRatio;
        int classCount;
        int methodCount;
        double averageMethodLength;
        List<String> qualityIssues;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class QualityMetricsBuilder {}
        
        public boolean meetsQualityStandards() {
            return qualityIssues.isEmpty() && 
                   commentRatio >= 0.1 && 
                   averageMethodLength <= 30;
        }
    }
    
    /**
     * Domain logic: Validate artifact completeness
     */
    public ArtifactValidationResult validate() {
        List<String> errors = new java.util.ArrayList<>();
        
        if (sourceFiles == null || sourceFiles.isEmpty()) {
            errors.add("No source files generated");
        }
        
        if (buildConfig == null) {
            errors.add("Build configuration missing");
        }
        
        // Check for at least one main class
        boolean hasMainClass = sourceFiles != null && sourceFiles.stream()
            .anyMatch(f -> !f.isTestFile() && f.getContent().contains("public class"));
        
        if (!hasMainClass) {
            errors.add("No main classes found");
        }
        
        return new ArtifactValidationResult(errors.isEmpty(), errors);
    }
    
    /**
     * Domain logic: Count production vs test files
     */
    public FileStatistics getFileStatistics() {
        if (sourceFiles == null) {
            return new FileStatistics(0, 0, 0);
        }
        
        long productionFiles = sourceFiles.stream().filter(f -> !f.isTestFile()).count();
        long testFiles = sourceFiles.stream().filter(SourceFile::isTestFile).count();
        
        return new FileStatistics(
            sourceFiles.size(),
            (int) productionFiles,
            (int) testFiles
        );
    }
    
    /**
     * Domain logic: Get total lines of code
     */
    public int getTotalLinesOfCode() {
        if (sourceFiles == null) {
            return 0;
        }
        return sourceFiles.stream()
            .mapToInt(SourceFile::getLineCount)
            .sum();
    }
    
    /**
     * Validation result
     */
    @Value
    public static class ArtifactValidationResult {
        boolean valid;
        List<String> errors;
    }
    
    /**
     * File statistics
     */
    @Value
    public static class FileStatistics {
        int totalFiles;
        int productionFiles;
        int testFiles;
        
        public double getTestRatio() {
            return totalFiles == 0 ? 0 : (double) testFiles / totalFiles;
        }
    }
}
