package com.therighthandapp.agentmesh.agents.reviewer.domain;

import lombok.Builder;
import lombok.Value;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Domain Model: Review Report
 * 
 * Rich domain model representing a comprehensive code review report generated by ReviewerAgent.
 * Contains quality issues, security concerns, best practice violations, and improvement suggestions.
 * 
 * Hexagonal Architecture: This is a domain entity with validation logic.
 */
@Value
@Builder
public class ReviewReport {
    String reportId;
    String codeArtifactId;
    String projectName;
    String description;
    
    // Review results
    OverallScore overallScore;
    List<QualityIssue> qualityIssues;
    List<SecurityIssue> securityIssues;
    List<BestPracticeViolation> bestPracticeViolations;
    List<Suggestion> suggestions;
    
    // Metrics
    CodeMetrics codeMetrics;
    ComplexityAnalysis complexityAnalysis;
    
    // Metadata
    LocalDateTime reviewedAt;
    String reviewerVersion;
    
    /**
     * Value Object: Overall Score
     */
    @Value
    @Builder
    public static class OverallScore {
        Integer totalScore;        // 0-100
        Integer qualityScore;      // 0-100
        Integer securityScore;     // 0-100
        Integer maintainabilityScore;  // 0-100
        String grade;              // A+, A, B, C, D, F
        String summary;
    }
    
    /**
     * Value Object: Quality Issue
     */
    @Value
    @Builder
    public static class QualityIssue {
        String issueId;
        Severity severity;
        String category;           // e.g., "Code Smell", "Bug Risk", "Performance"
        String title;
        String description;
        String filePath;
        Integer lineNumber;
        String codeSnippet;
        String recommendation;
        
        public enum Severity {
            CRITICAL,
            HIGH,
            MEDIUM,
            LOW,
            INFO
        }
    }
    
    /**
     * Value Object: Security Issue
     */
    @Value
    @Builder
    public static class SecurityIssue {
        String issueId;
        Severity severity;
        String category;           // e.g., "SQL Injection", "XSS", "Hardcoded Secret"
        String title;
        String description;
        String filePath;
        Integer lineNumber;
        String codeSnippet;
        String cweId;              // Common Weakness Enumeration ID
        String remediation;
        
        public enum Severity {
            CRITICAL,
            HIGH,
            MEDIUM,
            LOW
        }
    }
    
    /**
     * Value Object: Best Practice Violation
     */
    @Value
    @Builder
    public static class BestPracticeViolation {
        String violationId;
        String category;           // e.g., "Naming Convention", "Exception Handling"
        String title;
        String description;
        String filePath;
        Integer lineNumber;
        String codeSnippet;
        String recommendation;
        String reference;          // Link to documentation
    }
    
    /**
     * Value Object: Suggestion
     */
    @Value
    @Builder
    public static class Suggestion {
        String suggestionId;
        String category;           // e.g., "Refactoring", "Optimization", "Documentation"
        String title;
        String description;
        String filePath;
        Integer lineNumber;
        String currentCode;
        String suggestedCode;
        String benefit;
        Integer impactScore;       // 1-10
    }
    
    /**
     * Value Object: Code Metrics
     */
    @Value
    @Builder
    public static class CodeMetrics {
        Integer totalFiles;
        Integer totalLines;
        Integer codeLines;
        Integer commentLines;
        Double commentRatio;
        Integer duplicatedLines;
        Double duplicationRatio;
        Map<String, Integer> languageDistribution;
    }
    
    /**
     * Value Object: Complexity Analysis
     */
    @Value
    @Builder
    public static class ComplexityAnalysis {
        Double averageCyclomaticComplexity;
        Integer maxCyclomaticComplexity;
        String mostComplexMethod;
        String mostComplexFile;
        List<String> complexMethods;  // Methods with complexity > threshold
        Integer cognitiveComplexity;
        String complexityGrade;       // A, B, C, D, F
    }
    
    /**
     * Validates the review report
     */
    public void validate() {
        if (reportId == null || reportId.isBlank()) {
            throw new IllegalStateException("Review report must have an ID");
        }
        
        if (codeArtifactId == null || codeArtifactId.isBlank()) {
            throw new IllegalStateException("Review report must reference a code artifact");
        }
        
        if (overallScore == null) {
            throw new IllegalStateException("Review report must have an overall score");
        }
        
        if (overallScore.getTotalScore() < 0 || overallScore.getTotalScore() > 100) {
            throw new IllegalStateException("Overall score must be between 0 and 100");
        }
    }
    
    /**
     * Gets total number of issues
     */
    public Integer getTotalIssues() {
        int total = 0;
        if (qualityIssues != null) total += qualityIssues.size();
        if (securityIssues != null) total += securityIssues.size();
        if (bestPracticeViolations != null) total += bestPracticeViolations.size();
        return total;
    }
    
    /**
     * Gets critical and high severity issue count
     */
    public Integer getCriticalIssueCount() {
        int count = 0;
        
        if (qualityIssues != null) {
            count += qualityIssues.stream()
                .filter(issue -> issue.getSeverity() == QualityIssue.Severity.CRITICAL || 
                                issue.getSeverity() == QualityIssue.Severity.HIGH)
                .count();
        }
        
        if (securityIssues != null) {
            count += securityIssues.stream()
                .filter(issue -> issue.getSeverity() == SecurityIssue.Severity.CRITICAL || 
                                issue.getSeverity() == SecurityIssue.Severity.HIGH)
                .count();
        }
        
        return count;
    }
    
    /**
     * Checks if review passed (score >= 70)
     */
    public Boolean isPassed() {
        return overallScore != null && overallScore.getTotalScore() >= 70;
    }
    
    /**
     * Gets summary statistics
     */
    public Map<String, Object> getSummaryStatistics() {
        return Map.of(
            "totalIssues", getTotalIssues(),
            "criticalIssues", getCriticalIssueCount(),
            "totalScore", overallScore != null ? overallScore.getTotalScore() : 0,
            "grade", overallScore != null ? overallScore.getGrade() : "N/A",
            "passed", isPassed(),
            "qualityIssues", qualityIssues != null ? qualityIssues.size() : 0,
            "securityIssues", securityIssues != null ? securityIssues.size() : 0,
            "suggestions", suggestions != null ? suggestions.size() : 0
        );
    }
}
