package com.therighthandapp.agentmesh.agents.planner.domain;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.Builder;
import lombok.Value;
import lombok.With;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Domain Model: ExecutionPlan
 * 
 * Represents the comprehensive development plan generated by the Planner Agent.
 * This is an immutable value object that encapsulates all information needed
 * for the downstream agents (Coder, Tester) to execute the project.
 * 
 * DDD: This is a rich domain model, not an anemic data structure.
 * It contains business logic for validation and plan analysis.
 */
@Value
@Builder
@With
@JsonDeserialize(builder = ExecutionPlan.ExecutionPlanBuilder.class)
public class ExecutionPlan {
    
    String planId;
    String srsId;
    String srsUrl;
    String projectTitle;
    LocalDateTime generatedAt;
    
    List<Module> modules;
    FileStructure fileStructure;
    TestingStrategy testingStrategy;
    TechStack techStack;
    EffortEstimate effortEstimate;
    
    Map<String, String> metadata;
    
    @JsonPOJOBuilder(withPrefix = "")
    public static class ExecutionPlanBuilder {}
    
    /**
     * Domain logic: Validate plan completeness
     */
    public PlanValidationResult validate() {
        List<String> allErrors = new java.util.ArrayList<>();
        
        if (modules == null || modules.isEmpty()) {
            allErrors.add("No modules defined in execution plan");
        }
        
        if (techStack == null || techStack.getPrimaryLanguages().isEmpty()) {
            allErrors.add("No technology stack defined");
        }
        
        if (testingStrategy == null) {
            allErrors.add("Testing strategy not defined");
        }
        
        // Validate each module
        if (modules != null) {
            for (Module module : modules) {
                ModuleValidationResult moduleResult = module.validate();
                if (!moduleResult.isValid()) {
                    allErrors.addAll(moduleResult.getErrors());
                }
            }
        }
        
        return allErrors.isEmpty() ? PlanValidationResult.valid() : PlanValidationResult.invalid(allErrors);
    }
    
    /**
     * Domain logic: Calculate total file count
     */
    public int getTotalFileCount() {
        if (modules == null) return 0;
        return modules.stream()
                .mapToInt(m -> m.getFiles().size())
                .sum();
    }
    
    /**
     * Domain logic: Get all unique dependencies
     */
    public List<String> getAllDependencies() {
        if (modules == null) return List.of();
        return modules.stream()
                .flatMap(m -> m.getDependencies().stream())
                .distinct()
                .toList();
    }
    
    /**
     * Value Object: Module
     * Represents a cohesive unit of functionality in the system
     */
    @Value
    @Builder
    @JsonDeserialize(builder = Module.ModuleBuilder.class)
    public static class Module {
        String name;
        String description;
        Priority priority;
        List<String> techStack;
        List<FileDefinition> files;
        List<String> dependencies; // Dependencies on other modules
        Map<String, String> configuration;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class ModuleBuilder {}
        
        public ModuleValidationResult validate() {
            List<String> moduleErrors = new java.util.ArrayList<>();
            
            if (name == null || name.isBlank()) {
                moduleErrors.add("Module name is required");
            }
            
            if (files == null || files.isEmpty()) {
                moduleErrors.add("Module must have at least one file");
            }
            
            if (techStack == null || techStack.isEmpty()) {
                moduleErrors.add("Module must specify technology stack");
            }
            
            return moduleErrors.isEmpty() ? 
                ModuleValidationResult.valid(name != null ? name : "unknown") : 
                ModuleValidationResult.invalid(name != null ? name : "unknown", moduleErrors);
        }
    }
    
    /**
     * Value Object: FileDefinition
     * Defines what file should be generated
     */
    @Value
    @Builder
    @JsonDeserialize(builder = FileDefinition.FileDefinitionBuilder.class)
    public static class FileDefinition {
        String path;
        String purpose;
        FileType type;
        List<String> dependencies; // Imports/requires
        List<String> requirements; // Which requirements it fulfills (FR-001, etc.)
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class FileDefinitionBuilder {}
        
        public enum FileType {
            SOURCE_CODE,
            CONFIGURATION,
            DOCUMENTATION,
            TEST,
            INFRASTRUCTURE
        }
    }
    
    /**
     * Value Object: FileStructure
     * Represents the overall directory organization
     */
    @Value
    @Builder
    @JsonDeserialize(builder = FileStructure.FileStructureBuilder.class)
    public static class FileStructure {
        String rootDirectory;
        Map<String, DirectoryNode> directories;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class FileStructureBuilder {}
        
        @Value
        @Builder
        @JsonDeserialize(builder = DirectoryNode.DirectoryNodeBuilder.class)
        public static class DirectoryNode {
            String name;
            String purpose;
            List<String> files;
            Map<String, DirectoryNode> subdirectories;
            
            @JsonPOJOBuilder(withPrefix = "")
            public static class DirectoryNodeBuilder {}
        }
    }
    
    /**
     * Value Object: TestingStrategy
     */
    @Value
    @Builder
    @JsonDeserialize(builder = TestingStrategy.TestingStrategyBuilder.class)
    public static class TestingStrategy {
        int targetCoveragePercent;
        List<String> testingFrameworks;
        List<TestCategory> testCategories;
        List<String> criticalPaths;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class TestingStrategyBuilder {}
        
        @Value
        @Builder
        @JsonDeserialize(builder = TestCategory.TestCategoryBuilder.class)
        public static class TestCategory {
            String name;
            String description;
            int estimatedTestCount;
            
            @JsonPOJOBuilder(withPrefix = "")
            public static class TestCategoryBuilder {}
        }
    }
    
    /**
     * Value Object: TechStack
     */
    @Value
    @Builder
    @JsonDeserialize(builder = TechStack.TechStackBuilder.class)
    public static class TechStack {
        List<String> primaryLanguages;
        List<String> frameworks;
        List<String> libraries;
        List<String> databases;
        List<String> infrastructure;
        String architecturePattern; // e.g., "Microservices", "Monolith", "Layered"
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class TechStackBuilder {}
    }
    
    /**
     * Value Object: EffortEstimate
     */
    @Value
    @Builder
    @JsonDeserialize(builder = EffortEstimate.EffortEstimateBuilder.class)
    public static class EffortEstimate {
        int totalHours;
        Map<String, Integer> hoursByModule;
        int estimatedLinesOfCode;
        DevelopmentPhase[] phases;
        
        @JsonPOJOBuilder(withPrefix = "")
        public static class EffortEstimateBuilder {}
        
        @Value
        @Builder
        @JsonDeserialize(builder = DevelopmentPhase.DevelopmentPhaseBuilder.class)
        public static class DevelopmentPhase {
            String name;
            int durationDays;
            List<String> tasks;
            
            @JsonPOJOBuilder(withPrefix = "")
            public static class DevelopmentPhaseBuilder {}
        }
    }
    
    /**
     * Enum: Priority
     */
    public enum Priority {
        CRITICAL,
        HIGH,
        MEDIUM,
        LOW
    }
    
    /**
     * Validation Results
     */
    @Value
    public static class PlanValidationResult {
        List<String> errors;
        
        public static PlanValidationResult valid() {
            return new PlanValidationResult(List.of());
        }
        
        public static PlanValidationResult invalid(List<String> errors) {
            return new PlanValidationResult(errors);
        }
        
        public boolean isValid() {
            return errors.isEmpty();
        }
    }
    
    @Value
    public static class ModuleValidationResult {
        String moduleName;
        List<String> errors;
        
        public static ModuleValidationResult valid(String moduleName) {
            return new ModuleValidationResult(moduleName, List.of());
        }
        
        public static ModuleValidationResult invalid(String moduleName, List<String> errors) {
            return new ModuleValidationResult(moduleName, errors);
        }
        
        public boolean isValid() {
            return errors.isEmpty();
        }
    }
}
