package com.therighthandapp.agentmesh.agents.tester.domain;

import lombok.Builder;
import lombok.Value;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Domain Model: Test Suite
 * 
 * Rich domain model representing a comprehensive test suite generated by TesterAgent.
 * Contains unit tests, integration tests, coverage analysis, and test recommendations.
 * 
 * Hexagonal Architecture: This is a domain entity with validation logic.
 */
@Value
@Builder
public class TestSuite {
    String testSuiteId;
    String codeArtifactId;
    String projectName;
    String description;
    
    // Test cases
    List<UnitTest> unitTests;
    List<IntegrationTest> integrationTests;
    List<E2ETest> e2eTests;
    
    // Coverage and quality
    CoverageReport coverage;
    TestQualityMetrics qualityMetrics;
    
    // Recommendations
    List<TestGap> testGaps;
    List<TestRecommendation> recommendations;
    
    // Metadata
    LocalDateTime generatedAt;
    String testerVersion;
    
    /**
     * Value Object: Unit Test
     */
    @Value
    @Builder
    public static class UnitTest {
        String testId;
        String className;
        String methodName;
        String testName;
        String description;
        TestType type;
        List<String> testCases;
        String testCode;
        List<String> assertions;
        List<String> mockedDependencies;
        String filePath;
        
        public enum TestType {
            POSITIVE,           // Happy path
            NEGATIVE,           // Error cases
            BOUNDARY,           // Edge cases
            EXCEPTION,          // Exception handling
            PERFORMANCE,        // Performance tests
            INTEGRATION         // Integration tests
        }
    }
    
    /**
     * Value Object: Integration Test
     */
    @Value
    @Builder
    public static class IntegrationTest {
        String testId;
        String testName;
        String description;
        List<String> componentsUnderTest;
        String testCode;
        List<String> dependencies;
        String setupCode;
        String teardownCode;
        String filePath;
    }
    
    /**
     * Value Object: End-to-End Test
     */
    @Value
    @Builder
    public static class E2ETest {
        String testId;
        String testName;
        String description;
        String scenario;
        List<String> steps;
        String testCode;
        String expectedOutcome;
        String filePath;
    }
    
    /**
     * Value Object: Coverage Report
     */
    @Value
    @Builder
    public static class CoverageReport {
        Double overallCoverage;         // 0-100
        Double lineCoverage;
        Double branchCoverage;
        Double methodCoverage;
        Integer totalLines;
        Integer coveredLines;
        Integer totalBranches;
        Integer coveredBranches;
        Integer totalMethods;
        Integer coveredMethods;
        Map<String, FileCoverage> fileCoverage;
        
        @Value
        @Builder
        public static class FileCoverage {
            String filePath;
            Double coverage;
            Integer totalLines;
            Integer coveredLines;
            List<Integer> uncoveredLines;
        }
    }
    
    /**
     * Value Object: Test Quality Metrics
     */
    @Value
    @Builder
    public static class TestQualityMetrics {
        Integer totalTests;
        Integer unitTestCount;
        Integer integrationTestCount;
        Integer e2eTestCount;
        Double assertionDensity;        // Assertions per test
        Double mockUsageRatio;          // Tests with mocks / total tests
        Double testComplexity;          // Average cyclomatic complexity
        String qualityGrade;            // A, B, C, D, F
    }
    
    /**
     * Value Object: Test Gap
     */
    @Value
    @Builder
    public static class TestGap {
        String gapId;
        GapType type;
        String description;
        String component;
        String filePath;
        String methodName;
        Severity severity;
        String recommendation;
        
        public enum GapType {
            MISSING_UNIT_TEST,
            MISSING_INTEGRATION_TEST,
            MISSING_EDGE_CASE,
            MISSING_ERROR_HANDLING,
            MISSING_PERFORMANCE_TEST,
            LOW_COVERAGE,
            UNTESTED_METHOD,
            UNTESTED_BRANCH
        }
        
        public enum Severity {
            CRITICAL,
            HIGH,
            MEDIUM,
            LOW
        }
    }
    
    /**
     * Value Object: Test Recommendation
     */
    @Value
    @Builder
    public static class TestRecommendation {
        String recommendationId;
        String category;
        String title;
        String description;
        String rationale;
        Integer impactScore;            // 1-10
        String suggestedTestCode;
    }
    
    /**
     * Validates the test suite
     */
    public void validate() {
        if (testSuiteId == null || testSuiteId.isBlank()) {
            throw new IllegalStateException("Test suite must have an ID");
        }
        
        if (codeArtifactId == null || codeArtifactId.isBlank()) {
            throw new IllegalStateException("Test suite must reference a code artifact");
        }
        
        if (getTotalTestCount() == 0) {
            throw new IllegalStateException("Test suite must contain at least one test");
        }
    }
    
    /**
     * Gets total number of tests
     */
    public Integer getTotalTestCount() {
        int total = 0;
        if (unitTests != null) total += unitTests.size();
        if (integrationTests != null) total += integrationTests.size();
        if (e2eTests != null) total += e2eTests.size();
        return total;
    }
    
    /**
     * Gets critical test gaps count
     */
    public Integer getCriticalGapsCount() {
        if (testGaps == null) return 0;
        return (int) testGaps.stream()
            .filter(gap -> gap.getSeverity() == TestGap.Severity.CRITICAL || 
                          gap.getSeverity() == TestGap.Severity.HIGH)
            .count();
    }
    
    /**
     * Checks if test suite meets quality standards
     */
    public Boolean meetsQualityStandards() {
        if (coverage == null || coverage.getOverallCoverage() < 70) {
            return false;
        }
        
        if (getCriticalGapsCount() > 0) {
            return false;
        }
        
        return getTotalTestCount() >= 10;
    }
    
    /**
     * Gets summary statistics
     */
    public Map<String, Object> getSummaryStatistics() {
        return Map.of(
            "totalTests", getTotalTestCount(),
            "unitTests", unitTests != null ? unitTests.size() : 0,
            "integrationTests", integrationTests != null ? integrationTests.size() : 0,
            "e2eTests", e2eTests != null ? e2eTests.size() : 0,
            "coverage", coverage != null ? coverage.getOverallCoverage() : 0.0,
            "criticalGaps", getCriticalGapsCount(),
            "meetsQuality", meetsQualityStandards(),
            "grade", qualityMetrics != null ? qualityMetrics.getQualityGrade() : "N/A"
        );
    }
}
